# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'postgres'
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback
