name: On Push

on:
  push:
    branches:
      - main
      - release/*
      - chuck/tsv3
jobs:
  test:
    uses: ./.github/workflows/test.yml
  artifact:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/artifact.yml
