name: On Push

on:
  push:
    branches:
      - main
      - release/*
    paths-ignore:
      - 'README.md'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  artifact:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/artifact.yml
